[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=-bulk-memory,-bulk-memory-opt",
  "-C", "link-args=--allow-undefined"
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = []
